name: gps_track
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  google_maps_flutter: ^2.2.3
  geolocator: ^9.0.2
  workmanager: ^0.5.1
  cloud_firestore: ^4.3.1
  firebase_core: ^2.4.1

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
   - assets/
